#!/bin/sh

make check_files VERSION=acc_mc_np
make check_files VERSION=acc_mc_np_downsample_new
make check_files VERSION=acc_mc_np_lut
make check_files VERSION=acc_mc_np_lut3_downsample
make check_files VERSION=acc_mc_np_lut4_downsample
make check_files VERSION=acc_mc_np_lut5_downsample
make check_files VERSION=acc_mc_np_rcw_downsample
make check_files VERSION=acc_mc_paramKN_downsample_new
make check_files VERSION=acc_multi_cycle_downsample
